### ISSUE TITLE
tlcgroup.com contact form agreement text hyper link 

### ISSUE THREAD

**Issue by 2016DigiTech** [hlxsites/tlcgrp#90] opened 2023-01-02 09:34 UTC
Hi Team,

1. Please make the bold **term** and **Privacy Policy.** 
2. Contact form submission fail error in the first attempt.  Accepts in the second submission. 
![image](https://user-images.githubusercontent.com/112628085/210213712-a6733eec-44af-4f46-b2ae-1ba0e2fd8ee8.png)
3. Contact form leads details automatic drop on Email Id, 
  kamini.sharma@tlcgroup.com, shailendra@tlcgroup.com, puneeta.kaul@tlcgroup.com,  azam.md@tlcgroup.com, 
4. Contact form validation missing checkbox.

**Comment by rofe** [comment] 2023-01-19 22:10
@2016DigiTech Please use separate issues for different matters.
1. is a simple CSS change. you can make this in `form.css` (see #98)
2. Duplicate of #95 
3. Duplicate of #97 
4. What do you mean by that? If you mean the recaptcha, this is the new v3 which does automatic human verification. It only asks for user interaction in rare cases.

**Closed as completed** 2023-01-20 15:39 UTC
